// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/VivaLaPanda/isle/api/models"
)

// NewUserCreatedCode is the HTTP code returned for type NewUserCreated
const NewUserCreatedCode int = 201

/*NewUserCreated Null response

swagger:response newUserCreated
*/
type NewUserCreated struct {
}

// NewNewUserCreated creates NewUserCreated with default headers values
func NewNewUserCreated() *NewUserCreated {

	return &NewUserCreated{}
}

// WriteResponse to the client
func (o *NewUserCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*NewUserDefault unexpected error

swagger:response newUserDefault
*/
type NewUserDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNewUserDefault creates NewUserDefault with default headers values
func NewNewUserDefault(code int) *NewUserDefault {
	if code <= 0 {
		code = 500
	}

	return &NewUserDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the new user default response
func (o *NewUserDefault) WithStatusCode(code int) *NewUserDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the new user default response
func (o *NewUserDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the new user default response
func (o *NewUserDefault) WithPayload(payload *models.Error) *NewUserDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new user default response
func (o *NewUserDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewUserDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
