// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Isle Network
This is an API meant to interface with the Isle Network database to serve entities to a front-end interface. The reference server is written and Go and the reference client is in Javascript


    Schemes:
      http
    Host: virtserver.swaggerhub.com
    BasePath: /isle/1.0.0
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
