// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/VivaLaPanda/isle/api/models"
)

// GetPostByIDOKCode is the HTTP code returned for type GetPostByIDOK
const GetPostByIDOKCode int = 200

/*GetPostByIDOK Expected response to a valid request

swagger:response getPostByIdOK
*/
type GetPostByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.ContentNode `json:"body,omitempty"`
}

// NewGetPostByIDOK creates GetPostByIDOK with default headers values
func NewGetPostByIDOK() *GetPostByIDOK {

	return &GetPostByIDOK{}
}

// WithPayload adds the payload to the get post by Id o k response
func (o *GetPostByIDOK) WithPayload(payload *models.ContentNode) *GetPostByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get post by Id o k response
func (o *GetPostByIDOK) SetPayload(payload *models.ContentNode) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetPostByIDDefault unexpected error

swagger:response getPostByIdDefault
*/
type GetPostByIDDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetPostByIDDefault creates GetPostByIDDefault with default headers values
func NewGetPostByIDDefault(code int) *GetPostByIDDefault {
	if code <= 0 {
		code = 500
	}

	return &GetPostByIDDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get post by Id default response
func (o *GetPostByIDDefault) WithStatusCode(code int) *GetPostByIDDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get post by Id default response
func (o *GetPostByIDDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get post by Id default response
func (o *GetPostByIDDefault) WithPayload(payload *models.Error) *GetPostByIDDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get post by Id default response
func (o *GetPostByIDDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPostByIDDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
