// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/VivaLaPanda/isle-api/models"
)

// GetPostByIDHandlerFunc turns a function with the right signature into a get post by Id handler
type GetPostByIDHandlerFunc func(GetPostByIDParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn GetPostByIDHandlerFunc) Handle(params GetPostByIDParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// GetPostByIDHandler interface for that can handle valid get post by Id params
type GetPostByIDHandler interface {
	Handle(GetPostByIDParams, *models.Principal) middleware.Responder
}

// NewGetPostByID creates a new http.Handler for the get post by Id operation
func NewGetPostByID(ctx *middleware.Context, handler GetPostByIDHandler) *GetPostByID {
	return &GetPostByID{Context: ctx, Handler: handler}
}

/*GetPostByID swagger:route GET /posts/{postId} posts getPostById

Query for a specific post

*/
type GetPostByID struct {
	Context *middleware.Context
	Handler GetPostByIDHandler
}

func (o *GetPostByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetPostByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
