// Code generated by go-swagger; DO NOT EDIT.

package posts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/VivaLaPanda/isle/api/models"
)

// NewPostCreatedCode is the HTTP code returned for type NewPostCreated
const NewPostCreatedCode int = 201

/*NewPostCreated Null response

swagger:response newPostCreated
*/
type NewPostCreated struct {
}

// NewNewPostCreated creates NewPostCreated with default headers values
func NewNewPostCreated() *NewPostCreated {

	return &NewPostCreated{}
}

// WriteResponse to the client
func (o *NewPostCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*NewPostDefault unexpected error

swagger:response newPostDefault
*/
type NewPostDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNewPostDefault creates NewPostDefault with default headers values
func NewNewPostDefault(code int) *NewPostDefault {
	if code <= 0 {
		code = 500
	}

	return &NewPostDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the new post default response
func (o *NewPostDefault) WithStatusCode(code int) *NewPostDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the new post default response
func (o *NewPostDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the new post default response
func (o *NewPostDefault) WithPayload(payload *models.Error) *NewPostDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new post default response
func (o *NewPostDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewPostDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
