// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/VivaLaPanda/isle-api/models"
)

// NewTagHandlerFunc turns a function with the right signature into a new tag handler
type NewTagHandlerFunc func(NewTagParams, *models.Principal) middleware.Responder

// Handle executing the request and returning a response
func (fn NewTagHandlerFunc) Handle(params NewTagParams, principal *models.Principal) middleware.Responder {
	return fn(params, principal)
}

// NewTagHandler interface for that can handle valid new tag params
type NewTagHandler interface {
	Handle(NewTagParams, *models.Principal) middleware.Responder
}

// NewNewTag creates a new http.Handler for the new tag operation
func NewNewTag(ctx *middleware.Context, handler NewTagHandler) *NewTag {
	return &NewTag{Context: ctx, Handler: handler}
}

/*NewTag swagger:route POST /tags tags newTag

Make new tag

*/
type NewTag struct {
	Context *middleware.Context
	Handler NewTagHandler
}

func (o *NewTag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewNewTagParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.Principal
	if uprinc != nil {
		principal = uprinc.(*models.Principal) // this is really a models.Principal, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
