// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUpdateTagParams creates a new UpdateTagParams object
// no default values defined in spec.
func NewUpdateTagParams() UpdateTagParams {

	return UpdateTagParams{}
}

// UpdateTagParams contains all the bound params for the update tag operation
// typically these are obtained from a http.Request
//
// swagger:parameters updateTag
type UpdateTagParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The id of the tag to update
	  Required: true
	  In: path
	*/
	TagID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateTagParams() beforehand.
func (o *UpdateTagParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTagID, rhkTagID, _ := route.Params.GetOK("tagId")
	if err := o.bindTagID(rTagID, rhkTagID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *UpdateTagParams) bindTagID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.TagID = raw

	return nil
}
