// Code generated by go-swagger; DO NOT EDIT.

package tags

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"

	models "github.com/VivaLaPanda/isle-api/models"
)

// UpdateTagHandlerFunc turns a function with the right signature into a update tag handler
type UpdateTagHandlerFunc func(UpdateTagParams, *models.User) middleware.Responder

// Handle executing the request and returning a response
func (fn UpdateTagHandlerFunc) Handle(params UpdateTagParams, principal *models.User) middleware.Responder {
	return fn(params, principal)
}

// UpdateTagHandler interface for that can handle valid update tag params
type UpdateTagHandler interface {
	Handle(UpdateTagParams, *models.User) middleware.Responder
}

// NewUpdateTag creates a new http.Handler for the update tag operation
func NewUpdateTag(ctx *middleware.Context, handler UpdateTagHandler) *UpdateTag {
	return &UpdateTag{Context: ctx, Handler: handler}
}

/*UpdateTag swagger:route PUT /tags/{tagId} tags updateTag

Update a tag

*/
type UpdateTag struct {
	Context *middleware.Context
	Handler UpdateTagHandler
}

func (o *UpdateTag) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewUpdateTagParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *models.User
	if uprinc != nil {
		principal = uprinc.(*models.User) // this is really a models.User, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
