// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCommentsByIDHandlerFunc turns a function with the right signature into a get comments by Id handler
type GetCommentsByIDHandlerFunc func(GetCommentsByIDParams, *VivaLaPanda) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommentsByIDHandlerFunc) Handle(params GetCommentsByIDParams, principal *VivaLaPanda) middleware.Responder {
	return fn(params, principal)
}

// GetCommentsByIDHandler interface for that can handle valid get comments by Id params
type GetCommentsByIDHandler interface {
	Handle(GetCommentsByIDParams, *VivaLaPanda) middleware.Responder
}

// NewGetCommentsByID creates a new http.Handler for the get comments by Id operation
func NewGetCommentsByID(ctx *middleware.Context, handler GetCommentsByIDHandler) *GetCommentsByID {
	return &GetCommentsByID{Context: ctx, Handler: handler}
}

/*GetCommentsByID swagger:route GET /comments/{commentId} comments getCommentsById

Query for a specific comment

*/
type GetCommentsByID struct {
	Context *middleware.Context
	Handler GetCommentsByIDHandler
}

func (o *GetCommentsByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCommentsByIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *VivaLaPanda
	if uprinc != nil {
		principal = uprinc.(*VivaLaPanda) // this is really a VivaLaPanda, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
