// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCommentsByIDParams creates a new GetCommentsByIDParams object
// no default values defined in spec.
func NewGetCommentsByIDParams() GetCommentsByIDParams {

	return GetCommentsByIDParams{}
}

// GetCommentsByIDParams contains all the bound params for the get comments by Id operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCommentsById
type GetCommentsByIDParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The id of the comment to retrieve
	  Required: true
	  In: path
	*/
	CommentID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCommentsByIDParams() beforehand.
func (o *GetCommentsByIDParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rCommentID, rhkCommentID, _ := route.Params.GetOK("commentId")
	if err := o.bindCommentID(rCommentID, rhkCommentID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetCommentsByIDParams) bindCommentID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.CommentID = raw

	return nil
}
