// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetCommentsHandlerFunc turns a function with the right signature into a get comments handler
type GetCommentsHandlerFunc func(GetCommentsParams, *VivaLaPanda) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCommentsHandlerFunc) Handle(params GetCommentsParams, principal *VivaLaPanda) middleware.Responder {
	return fn(params, principal)
}

// GetCommentsHandler interface for that can handle valid get comments params
type GetCommentsHandler interface {
	Handle(GetCommentsParams, *VivaLaPanda) middleware.Responder
}

// NewGetComments creates a new http.Handler for the get comments operation
func NewGetComments(ctx *middleware.Context, handler GetCommentsHandler) *GetComments {
	return &GetComments{Context: ctx, Handler: handler}
}

/*GetComments swagger:route GET /comments comments getComments

Query comments

*/
type GetComments struct {
	Context *middleware.Context
	Handler GetCommentsHandler
}

func (o *GetComments) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetCommentsParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal *VivaLaPanda
	if uprinc != nil {
		principal = uprinc.(*VivaLaPanda) // this is really a VivaLaPanda, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
