// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/VivaLaPanda/isle/api/models"
)

// GetCommentsOKCode is the HTTP code returned for type GetCommentsOK
const GetCommentsOKCode int = 200

/*GetCommentsOK An paged array of pets

swagger:response getCommentsOK
*/
type GetCommentsOK struct {
	/*A link to the next page of responses

	 */
	XNext string `json:"x-next"`

	/*
	  In: Body
	*/
	Payload models.ContentNodes `json:"body,omitempty"`
}

// NewGetCommentsOK creates GetCommentsOK with default headers values
func NewGetCommentsOK() *GetCommentsOK {

	return &GetCommentsOK{}
}

// WithXNext adds the xNext to the get comments o k response
func (o *GetCommentsOK) WithXNext(xNext string) *GetCommentsOK {
	o.XNext = xNext
	return o
}

// SetXNext sets the xNext to the get comments o k response
func (o *GetCommentsOK) SetXNext(xNext string) {
	o.XNext = xNext
}

// WithPayload adds the payload to the get comments o k response
func (o *GetCommentsOK) WithPayload(payload models.ContentNodes) *GetCommentsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments o k response
func (o *GetCommentsOK) SetPayload(payload models.ContentNodes) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	// response header x-next

	xNext := o.XNext
	if xNext != "" {
		rw.Header().Set("x-next", xNext)
	}

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		payload = make(models.ContentNodes, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}

}

/*GetCommentsDefault unexpected error

swagger:response getCommentsDefault
*/
type GetCommentsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCommentsDefault creates GetCommentsDefault with default headers values
func NewGetCommentsDefault(code int) *GetCommentsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCommentsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get comments default response
func (o *GetCommentsDefault) WithStatusCode(code int) *GetCommentsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get comments default response
func (o *GetCommentsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get comments default response
func (o *GetCommentsDefault) WithPayload(payload *models.Error) *GetCommentsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get comments default response
func (o *GetCommentsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCommentsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
