// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/VivaLaPanda/isle/api/models"
)

// NewCommentCreatedCode is the HTTP code returned for type NewCommentCreated
const NewCommentCreatedCode int = 201

/*NewCommentCreated Null response

swagger:response newCommentCreated
*/
type NewCommentCreated struct {
}

// NewNewCommentCreated creates NewCommentCreated with default headers values
func NewNewCommentCreated() *NewCommentCreated {

	return &NewCommentCreated{}
}

// WriteResponse to the client
func (o *NewCommentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*NewCommentDefault unexpected error

swagger:response newCommentDefault
*/
type NewCommentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewNewCommentDefault creates NewCommentDefault with default headers values
func NewNewCommentDefault(code int) *NewCommentDefault {
	if code <= 0 {
		code = 500
	}

	return &NewCommentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the new comment default response
func (o *NewCommentDefault) WithStatusCode(code int) *NewCommentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the new comment default response
func (o *NewCommentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the new comment default response
func (o *NewCommentDefault) WithPayload(payload *models.Error) *NewCommentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the new comment default response
func (o *NewCommentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *NewCommentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
