// Code generated by go-swagger; DO NOT EDIT.

package comments

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/VivaLaPanda/isle/api/models"
)

// UpdateCommentCreatedCode is the HTTP code returned for type UpdateCommentCreated
const UpdateCommentCreatedCode int = 201

/*UpdateCommentCreated Null response

swagger:response updateCommentCreated
*/
type UpdateCommentCreated struct {
}

// NewUpdateCommentCreated creates UpdateCommentCreated with default headers values
func NewUpdateCommentCreated() *UpdateCommentCreated {

	return &UpdateCommentCreated{}
}

// WriteResponse to the client
func (o *UpdateCommentCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(201)
}

/*UpdateCommentDefault unexpected error

swagger:response updateCommentDefault
*/
type UpdateCommentDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewUpdateCommentDefault creates UpdateCommentDefault with default headers values
func NewUpdateCommentDefault(code int) *UpdateCommentDefault {
	if code <= 0 {
		code = 500
	}

	return &UpdateCommentDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the update comment default response
func (o *UpdateCommentDefault) WithStatusCode(code int) *UpdateCommentDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the update comment default response
func (o *UpdateCommentDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the update comment default response
func (o *UpdateCommentDefault) WithPayload(payload *models.Error) *UpdateCommentDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update comment default response
func (o *UpdateCommentDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdateCommentDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
